# Generated by Django 4.2.6 on 2023-10-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_baskets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
